### ISSUE TITLE
Support for Sign

### ISSUE THREAD

**Issue by Niach** [jibon57/nativescript-simple-libsodium#1]
Hello,
Id like to add support for signing. I see both native libs support it, how should i go forward to add the common wrappers?

**Comment by jibon57** [comment]
Sorry, I don't have any idea, what are you talking about...

**Comment by Niach** [comment]
i want to add 

- crypto_sign_keypair
- crypto_sign
- crypto_sign_open

from https://libsodium.gitbook.io/doc/public-key_cryptography/public-key_signatures

how can i achieve this? sry for my bad english

**Comment by jibon57** [comment]
You can follow the instructions there. You can have a look already implemented functions.
